 export default Details={
    "OPR_ID": {
      "MAINFLTPLAN": {
        "ROW": [
          {
            "WPT": "WMSA",
            "MORA": "",
            "TRK": 0,
            "FL": "CLB",
            "WV": "097/011",
            "IAS": "...",
            "EET": 0,
            "EFB": "",
            "GWT": "...",
            "LAT": "N0307.86",
            "LON": "E10132.88",
            "TAS": "",
            "OAT": "...",
            "DST": 0,
            "FRE": "",
            "AWY": "SUKA1S",
            "MK": "...",
            "MH": "",
            "GS": "",
            "TDV": "...",
            "DRM": 172,
            "TRMG": "00:46",
            "TTLB": "...",
            "RQF": "..."
          },
          {
            "WPT": "SM",
            "MORA": 86,
            "TRK": 148,
            "FL": "CLB",
            "WV": "099/010",
            "IAS": "...",
            "EET": 1,
            "EFB": "...",
            "GWT": "...",
            "LAT": "N0305.28",
            "LON": "E10134.41",
            "TAS": 0,
            "OAT": "...",
         
            "DST": 3,
            "FRE": "355KHz",
            "AWY": "SUKA1S",
            "MK": "...",
            "MH": 145,
            "GS": 165,
            "TDV": "...",
            "DRM": 169,
            "TRMG": "00:45",
            "TTLB": "...",
            "RQF": "..."
          },
          {
            "WPT": "VBA",
            "MORA": 86,
            "TRK": 334,
            "FL": "CLB",
            "WV": "090/010",
            "IAS": "...",
            "EET": 5,
            "EFB": "...",
            "GWT": "...",
            "LAT": "N0319.48",
            "LON": "E10127.41",
            "TAS": 179,
            "OAT": "...",
            "DST": 16,
            "FRE": "114.7Hz",
            "AWY": "B466",
            "MK": "...",
            "MH": 337,
            "GS": 183,
            "TDV": "...",
            "DRM": 153,
            "TRMG": "00:40",
            "TTLB": "...",
            "RQF": "..."
          },
          {
            "WPT": "SUKAT",
            "MORA": 86,
            "TRK": 301,
            "FL": "CLB",
            "WV": "093/016",
            "IAS": "...",
            "EET": 9,
            "EFB": "...",
            "GWT": "...",
            "LAT": "N0335.41",
            "LON": "E10101.20",
            "TAS": 192,
            "OAT": "...",
            "DST": 31,
            "FRE": "",
            "AWY": "A457",
            "MK": "...",
            "MH": 303,
            "GS": 206,
            "TDV": "...",
            "DRM": 122,
            "TRMG": "00:31",
            "TTLB": "...",
            "RQF": "..."
          },
          {
            "WPT": "TOC",
            "MORA": 18,
            "TRK": 336,
            "FL": 160,
            "WV": "094/018",
            "IAS": "...",
            "EET": 3,
            "EFB": 245,
            "GWT": 20.05,
            "LAT": "N0344.54",
            "LON": "E10057.12",
            "TAS": 205,
            "OAT": "...",
            "DST": 10,
            "FRE": "",
            "AWY": "A457",
            "MK": "...",
            "MH": 340,
            "GS": 215,
            "TDV": "...",
            "DRM": 112,
            "TRMG": "00:28",
            "TTLB": 295,
            "RQF": 2256
          },
          {
            "WPT": "TEPUS",
            "MORA": 77,
            "TRK": 336,
            "FL": 160,
            "WV": "098/018",
            "IAS": 202,
            "EET": 6,
            "EFB": 70,
            "GWT": 19.98,
            "LAT": "N0410.21",
            "LON": "E10045.55",
            "TAS": 264,
            "OAT": 0,
            "DST": 28,
            "FRE": "",
            "AWY": "GORV2J",
            "MK": 201,
            "MH": 339,
            "GS": 273,
            "TDV": "P17",
            "DRM": 84,
            "TRMG": "00:22",
            "TTLB": 365,
            "RQF": 2186
          },
          {
            "WPT": "TOD",
            "MORA": 77,
            "TRK": 337,
            "FL": 160,
            "WV": "104/017",
            "IAS": 203,
            "EET": 9,
            "EFB": 103,
            "GWT": 19.87,
            "LAT": "N0448.86",
            "LON": "E10029.08",
            "TAS": 265,
            "OAT": -1,
            "DST": 42,
            "FRE": "",
            "AWY": "GORV2J",
            "MK": 203,
            "MH": 340,
            "GS": 276,
            "TDV": "P16",
            "DRM": 42,
            "TRMG": "00:13",
            "TTLB": 468,
            "RQF": 2083
          },
          {
            "WPT": "GORVU",
            "MORA": 77,
            "TRK": 337,
            "FL": "DES",
            "WV": "105/017",
            "IAS": "...",
            "EET": 0,
            "EFB": "...",
            "GWT": "...",
            "LAT": "N0449.43",
            "LON": "E10028.44",
            "TAS": 229,
            "OAT": "...",
            "DST": 1,
            "FRE": "",
            "AWY": "GORV2J",
            "MK": "...",
            "MH": 341,
            "GS": 237,
            "TDV": "...",
            "DRM": 41,
            "TRMG": "00:13",
            "TTLB": "...",
            "RQF": "..."
          },
          {
            "WPT": "AVLOM",
            "MORA": 77,
            "TRK": 308,
            "FL": "DES",
            "WV": "102/016",
            "IAS": "...",
            "EET": 2,
            "EFB": "...",
            "GWT": "...",
            "LAT": "N0454.69",
            "LON": "E10021.54",
            "TAS": 214,
            "OAT": "...",
            "DST": 9,
            "FRE": "",
            "AWY": "GORV2J",
            "MK": "...",
            "MH": 310,
            "GS": 230,
            "TDV": "...",
            "DRM": 32,
            "TRMG": "00:11",
            "TTLB": "...",
            "RQF": "..."
          },
          {
            "WPT": "KAMBU",
            "MORA": 84,
            "TRK": 308,
            "FL": "DES",
            "WV": "093/007",
            "IAS": "...",
            "EET": 4,
            "EFB": "...",
            "GWT": "...",
            "LAT": "N0502.34",
            "LON": "E10011.50",
            "TAS": 201,
            "OAT": "...",
            "DST": 13,
            "FRE": "",
            "AWY": "GORV2J",
            "MK": "...",
            "MH": 310,
            "GS": 216,
            "TDV": "...",
            "DRM": 19,
            "TRMG": "00:07",
            "TTLB": "...",
            "RQF": "..."
          },
          {
            "WPT": "IKODI",
            "MORA": 84,
            "TRK": 333,
            "FL": "DES",
            "WV": "090/005",
            "IAS": "...",
            "EET": 3,
            "EFB": "...",
            "GWT": "...",
            "LAT": "N0508.56",
            "LON": "E10008.23",
            "TAS": 130,
            "OAT": "...",
            "DST": 7,
            "FRE": "",
            "AWY": "",
            "MK": "...",
            "MH": 336,
            "GS": 133,
            "TDV": "...",
            "DRM": 12,
            "TRMG": "00:04",
            "TTLB": "...",
            "RQF": "..."
          },
          {
            "WPT": "WMKP",
            "MORA": 84,
            "TRK": 222,
            "FL": "DES",
            "WV": "083/007",
            "IAS": "...",
            "EET": 4,
            "EFB": 146,
            "GWT": 19.73,
            "LAT": "N0517.83",
            "LON": "E10016.60",
            "TAS": 0,
            "OAT": "...",
            "DST": 12,
            "FRE": "",
            "AWY": "",
            "MK": "...",
            "MH": 221,
            "GS": 175,
            "TDV": "...",
            "DRM": 0,
            "TRMG": "00:00",
            "TTLB": 615,
            "RQF": 1936
          }
        ]
      },
      "ALT1FP": {
        "ROW": [
          {
            "WPT": "WMKP",
            "MSA": "",
            "LAT": "N0517.83",
            "LON": "E10016.60",
            "TRK": 0,
            "TAS": "",
            "OAT": "...",
            "EET": 0,
            "EFB": "...",
            "DST": 0,
            "ST": 0,
            "SB": "...",
            "GWT": "...",
            "FL": "CLB",
            "WV": "083/007",
            "IAS": "...",
            "MH": "",
            "GS": "",
            "TDV": "...",
            "DRM": 158,
            "TRMG": "00:45",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "",
            "AWY": "KABO1E"
          },
          {
            "WPT": "VPG",
            "MSA": 84,
            "LAT": "N0516.76",
            "LON": "E10015.64",
            "TRK": 222,
            "TAS": 0,
            "EET": 5,
            "EFB": "...",
            "OAT": "...",
            "DST": 1,
            "ST": 0,
            "SB": "...",
            "GWT": "...",
            "FL": "CLB",
            "WV": "073/005",
            "IAS": "...",
            "MH": 221,
            "GS": 176,
            "TDV": "...",
            "DRM": 157,
            "TRMG": "00:45",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "116.2Hz",
            "AWY": "KABO1E"
          },
          {
            "WPT": "KABOT",
            "MSA": 77,
            "LAT": "N0454.70",
            "LON": "E10042.44",
            "TRK": 130,
            "TAS": 187,
            "EET": 2,
            "EFB": "...",
            "OAT": "...",
            "DST": 35,
            "ST": 12,
            "SB": "...",
            "GWT": "...",
            "FL": "CLB",
            "WV": "098/014",
            "IAS": "...",
            "MH": 128,
            "GS": 175,
            "TDV": "...",
            "DRM": 122,
            "TRMG": "00:33",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "",
            "AWY": "KABO1E"
          },
          {
            "WPT": "TOC",
            "MSA": 77,
            "LAT": "N0445.51",
            "LON": "E10053.23",
            "TRK": 131,
            "TAS": 200,
            "EET": 7,
            "EFB": "...",
            "OAT": "...",
            "DST": 14,
            "ST": 4,
            "SB": 216,
            "GWT": 19.34,
            "FL": 150,
            "WV": "103/016",
            "IAS": "...",
            "MH": 128,
            "GS": 185,
            "TDV": "...",
            "DRM": 108,
            "TRMG": "00:29",
            "TTLB": 216,
            "RQF": 1550,
            "FRE": "",
            "AWY": "KABO1E"
          },
          {
            "WPT": "VIH",
            "MSA": 95,
            "LAT": "N0434.41",
            "LON": "E10105.63",
            "TRK": 131,
            "TAS": 266,
            "EET": 2,
            "EFB": "...",
            "OAT": 1,
            "DST": 17,
            "ST": 4,
            "SB": 50,
            "GWT": 19.29,
            "FL": 150,
            "WV": "097/017",
            "IAS": 207,
            "MH": 129,
            "GS": 252,
            "TDV": "P16",
            "DRM": 91,
            "TRMG": "00:25",
            "TTLB": 264,
            "RQF": 1502,
            "FRE": "117.3Hz",
            "AWY": "A464"
          },
          {
            "WPT": "DAKUS",
            "MSA": 86,
            "LAT": "N0348.23",
            "LON": "E10119.50",
            "TRK": 164,
            "TAS": 266,
            "EET": 1,
            "EFB": "...",
            "OAT": 2,
            "DST": 48,
            "ST": 11,
            "SB": 130,
            "GWT": 19.16,
            "FL": 150,
            "WV": "094/017",
            "IAS": 207,
            "MH": 161,
            "GS": 261,
            "TDV": "P17",
            "DRM": 43,
            "TRMG": "00:14",
            "TTLB": 392,
            "RQF": 1374,
            "FRE": "",
            "AWY": "CE1"
          },
          {
            "WPT": "TOD",
            "MSA": 86,
            "LAT": "N0334.64",
            "LON": "E10122.89",
            "TRK": 166,
            "TAS": 266,
            "EET": 9,
            "EFB": "...",
            "OAT": 2,
            "DST": 14,
            "ST": 3,
            "SB": 40,
            "GWT": 19.13,
            "FL": 150,
            "WV": "093/019",
            "IAS": 207,
            "MH": 162,
            "GS": 261,
            "TDV": "P17",
            "DRM": 29,
            "TRMG": "00:11",
            "TTLB": 428,
            "RQF": 1338,
            "FRE": "",
            "AWY": "CE1"
          },
          {
            "WPT": "D343O",
            "MSA": 86,
            "LAT": "N0333.95",
            "LON": "E10123.20",
            "TRK": 166,
            "TAS": 228,
            "EET": 8,
            "EFB": "...",
            "OAT": "...",
            "DST": 1,
            "ST": 0,
            "SB": "...",
            "GWT": "...",
            "FL": "DES",
            "WV": "093/019",
            "IAS": "...",
            "MH": 161,
            "GS": 222,
            "TDV": "...",
            "DRM": 28,
            "TRMG": "00:11",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "",
            "AWY": "CE1"
          },
          {
            "WPT": "D343C",
            "MSA": 86,
            "LAT": "N0322.38",
            "LON": "E10126.57",
            "TRK": 164,
            "TAS": 201,
            "EET": 4,
            "EFB": "...",
            "OAT": "...",
            "DST": 12,
            "ST": 4,
            "SB": "...",
            "GWT": "...",
            "FL": "DES",
            "WV": "090/008",
            "IAS": "...",
            "MH": 159,
            "GS": 195,
            "TDV": "...",
            "DRM": 16,
            "TRMG": "00:07",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "",
            "AWY": "CE1"
          },
          {
            "WPT": "CE",
            "MSA": 86,
            "LAT": "N0317.70",
            "LON": "E10127.11",
            "TRK": 173,
            "TAS": 84,
            "OAT": "...",
            "EET": 5,
            "EFB": "...",
            "DST": 5,
            "ST": 4,
            "SB": "...",
            "GWT": "...",
            "FL": "DES",
            "WV": "090/008",
            "IAS": "...",
            "MH": 168,
            "GS": 83,
            "TDV": "...",
            "DRM": 11,
            "TRMG": "00:03",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "205KHz",
            "AWY": ""
          },
          {
            "WPT": "WMSA",
            "MSA": 86,
            "LAT": "N0307.86",
            "LON": "E10132.88",
            "TRK": 330,
            "TAS": 0,
            "EET": 2,
            "EFB": "...",
            "OAT": "...",
            "DST": 11,
            "ST": 3,
            "SB": 123,
            "GWT": 19,
            "FL": "DES",
            "WV": "097/011",
            "IAS": "...",
            "MH": 332,
            "GS": 176,
            "TDV": "...",
            "DRM": 0,
            "TRMG": "00:00",
            "TTLB": 552,
            "RQF": 1214,
            "FRE": "",
            "AWY": ""
          }
        ]
      },
      "ALT2FP": {
        "ROW": [
          {
            "WPT": "WMKP",
            "MSA": "",
            "LAT": "N0517.83",
            "LON": "E10016.60",
            "TRK": 0,
            "TAS": "",
            "OAT": "...",
            "EET": 0,
            "EFB": "...",
            "DST": 0,
            "ST": 0,
            "SB": "...",
            "GWT": "...",
            "FL": "CLB",
            "WV": "083/007",
            "IAS": "...",
            "MH": "",
            "GS": "",
            "TDV": "...",
            "DRM": 158,
            "TRMG": "00:45",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "",
            "AWY": "KABO1E"
          },
          {
            "WPT": "VPG",
            "MSA": 84,
            "LAT": "N0516.76",
            "LON": "E10015.64",
            "TRK": 222,
            "TAS": 0,
            "EET": 5,
            "EFB": "...",
            "OAT": "...",
            "DST": 1,
            "ST": 0,
            "SB": "...",
            "GWT": "...",
            "FL": "CLB",
            "WV": "073/005",
            "IAS": "...",
            "MH": 221,
            "GS": 176,
            "TDV": "...",
            "DRM": 157,
            "TRMG": "00:45",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "116.2Hz",
            "AWY": "KABO1E"
          },
          {
            "WPT": "KABOT",
            "MSA": 77,
            "LAT": "N0454.70",
            "LON": "E10042.44",
            "TRK": 130,
            "TAS": 187,
            "EET": 2,
            "EFB": "...",
            "OAT": "...",
            "DST": 35,
            "ST": 12,
            "SB": "...",
            "GWT": "...",
            "FL": "CLB",
            "WV": "098/014",
            "IAS": "...",
            "MH": 128,
            "GS": 175,
            "TDV": "...",
            "DRM": 122,
            "TRMG": "00:33",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "",
            "AWY": "KABO1E"
          },
          {
            "WPT": "TOC",
            "MSA": 77,
            "LAT": "N0445.51",
            "LON": "E10053.23",
            "TRK": 131,
            "TAS": 200,
            "EET": 7,
            "EFB": "...",
            "OAT": "...",
            "DST": 14,
            "ST": 4,
            "SB": 216,
            "GWT": 19.34,
            "FL": 150,
            "WV": "103/016",
            "IAS": "...",
            "MH": 128,
            "GS": 185,
            "TDV": "...",
            "DRM": 108,
            "TRMG": "00:29",
            "TTLB": 216,
            "RQF": 1550,
            "FRE": "",
            "AWY": "KABO1E"
          },
          {
            "WPT": "VIH",
            "MSA": 95,
            "LAT": "N0434.41",
            "LON": "E10105.63",
            "TRK": 131,
            "TAS": 266,
            "EET": 2,
            "EFB": "...",
            "OAT": 1,
            "DST": 17,
            "ST": 4,
            "SB": 50,
            "GWT": 19.29,
            "FL": 150,
            "WV": "097/017",
            "IAS": 207,
            "MH": 129,
            "GS": 252,
            "TDV": "P16",
            "DRM": 91,
            "TRMG": "00:25",
            "TTLB": 264,
            "RQF": 1502,
            "FRE": "117.3Hz",
            "AWY": "A464"
          },
          {
            "WPT": "DAKUS",
            "MSA": 86,
            "LAT": "N0348.23",
            "LON": "E10119.50",
            "TRK": 164,
            "TAS": 266,
            "EET": 1,
            "EFB": "...",
            "OAT": 2,
            "DST": 48,
            "ST": 11,
            "SB": 130,
            "GWT": 19.16,
            "FL": 150,
            "WV": "094/017",
            "IAS": 207,
            "MH": 161,
            "GS": 261,
            "TDV": "P17",
            "DRM": 43,
            "TRMG": "00:14",
            "TTLB": 392,
            "RQF": 1374,
            "FRE": "",
            "AWY": "CE1"
          },
          {
            "WPT": "TOD",
            "MSA": 86,
            "LAT": "N0334.64",
            "LON": "E10122.89",
            "TRK": 166,
            "TAS": 266,
            "EET": 9,
            "EFB": "...",
            "OAT": 2,
            "DST": 14,
            "ST": 3,
            "SB": 40,
            "GWT": 19.13,
            "FL": 150,
            "WV": "093/019",
            "IAS": 207,
            "MH": 162,
            "GS": 261,
            "TDV": "P17",
            "DRM": 29,
            "TRMG": "00:11",
            "TTLB": 428,
            "RQF": 1338,
            "FRE": "",
            "AWY": "CE1"
          },
          {
            "WPT": "D343O",
            "MSA": 86,
            "LAT": "N0333.95",
            "LON": "E10123.20",
            "TRK": 166,
            "TAS": 228,
            "EET": 8,
            "EFB": "...",
            "OAT": "...",
            "DST": 1,
            "ST": 0,
            "SB": "...",
            "GWT": "...",
            "FL": "DES",
            "WV": "093/019",
            "IAS": "...",
            "MH": 161,
            "GS": 222,
            "TDV": "...",
            "DRM": 28,
            "TRMG": "00:11",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "",
            "AWY": "CE1"
          },
          {
            "WPT": "D343C",
            "MSA": 86,
            "LAT": "N0322.38",
            "LON": "E10126.57",
            "TRK": 164,
            "TAS": 201,
            "EET": 4,
            "EFB": "...",
            "OAT": "...",
            "DST": 12,
            "ST": 4,
            "SB": "...",
            "GWT": "...",
            "FL": "DES",
            "WV": "090/008",
            "IAS": "...",
            "MH": 159,
            "GS": 195,
            "TDV": "...",
            "DRM": 16,
            "TRMG": "00:07",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "",
            "AWY": "CE1"
          },
          {
            "WPT": "CE",
            "MSA": 86,
            "LAT": "N0317.70",
            "LON": "E10127.11",
            "TRK": 173,
            "TAS": 84,
            "OAT": "...",
            "EET": 5,
            "EFB": "...",
            "DST": 5,
            "ST": 4,
            "SB": "...",
            "GWT": "...",
            "FL": "DES",
            "WV": "090/008",
            "IAS": "...",
            "MH": 168,
            "GS": 83,
            "TDV": "...",
            "DRM": 11,
            "TRMG": "00:03",
            "TTLB": "...",
            "RQF": "...",
            "FRE": "205KHz",
            "AWY": ""
          },
          {
            "WPT": "WMSA",
            "MSA": 86,
            "LAT": "N0307.86",
            "LON": "E10132.88",
            "TRK": 330,
            "TAS": 0,
            "EET": 2,
            "EFB": "...",
            "OAT": "...",
            "DST": 11,
            "ST": 3,
            "SB": 123,
            "GWT": 19,
            "FL": "DES",
            "WV": "097/011",
            "IAS": "...",
            "MH": 332,
            "GS": 176,
            "TDV": "...",
            "DRM": 0,
            "TRMG": "00:00",
            "TTLB": 552,
            "RQF": 1214,
            "FRE": "",
            "AWY": ""
          }
        ]
      },
      "FUEL": {
        "TRIP": {
          "ARPT": "WMKP",
          "FUEL": 615,
          "TIME": "00:51",
          "DIST": 172
        },
        "CONT": {
          "FUEL": 31,
          "TIME": "00:00"
        },
        "INSTARPT": {
          "FUEL": 120,
          "TIME": "00:08"
        },
        "ALT": {
          "ARPT": "WMSA",
          "FUEL": 622,
          "TIME": "00:45",
          "DIST": 158
        },
        "HOLD": {
          "FUEL": 390,
          "TIME": "00:45"
        },
        "MSF": {
          "FUEL": -602
        },
        "TAXI": {
          "FUEL": 50
        },
        "SURPLUS": {
          "FUEL": 2380,
          "TIME": "00:00"
        },
        "TANKFUEL": {
          "FUEL": 723.3
        },
        "MBF": {
          "FUEL": 2551
        },
        "MEXFUEL": 2380
      },
      "ALTFL": {
        "ROW": [
          {
            "FL": 120,
            "TRIPFUEL": 625,
            "TRIPTIME": "00:49"
          },
          {
            "FL": 140,
            "TRIPFUEL": 619,
            "TRIPTIME": "00:50"
          }
        ]
      },
      "ATCFLTPLN": {
        "L": [
          "(FPL-FY1440-IS",
          "-ATR72/M-SGDR/L",
          "-WMSA 1200",
          "-N0264 F160 WMSA SUKA1S VBA B466 SUKAT A457 TEPUS GORV2J WMKP",
          "-WMKP 0051 WMSA WMKL",
          "-PBN/B2C2D2O2 DOF/ REG/9M-FYF EET/ SEL/DPFK",
          "",
          "-E/0144 P/TBN A/WHITE ORANGEC/ZAKI UDDIN",
          ""
        ]
      },
      "FLTDET": {
        "FLTNO": "FY1440",
        "REG": "9M-FYF",
        "TYPE": "ATR72",
        "SRC": "SZB",
        "DES": "PEN",
        "ALT1NAME": "SZB",
        "ALT2NAME": "LGK",
        "DATE": "09/21/2023",
        "MZFW": 20800,
        "MLW": 22350,
        "MTOW": 22800,
        "EZFW": 17800,
        "ELW": 19600,
        "ETOW": 20300,
        "GCDDIST": 151,
        "ISADEV": 17,
        "FUELBIAS": 0,
        "IATASRC": "WMSA",
        "IATADES": "WMKP",
        "IATAALT1": "WMSA",
        "IATAALT2": "WMKL",
        "ESAD": 147,
        "AVGWC": "TL39",
        "TDISTEET": "151/00:51"
      }
    }
  }